### ISSUE TITLE
error: `DATABASE_URL` must be set to use query macros

### ISSUE THREAD

**Issue by FANLIYANG-OPS** [casbin-rs/sqlx-adapter#65]
this error originates in the macro `$crate::sqlx_macros::expand_query` (in Nightly builds, run with -Z macro-backtrace for more info)

![image](https://user-images.githubusercontent.com/20119253/158735546-128d5236-bcf9-4e46-9485-a8b785c96be6.png)
![image](https://user-images.githubusercontent.com/20119253/158735639-9ed4876c-dab2-44c5-ba1a-9960df741c30.png)
![image](https://user-images.githubusercontent.com/20119253/158735677-9af028d7-f667-471a-a278-1e8d47b68f6c.png)

**Comment by hsluoyz** [comment]
@PsiACE

**Comment by PsiACE** [comment]
ref readme

Rename sample.env to .env and put DATABASE_URL, POOL_SIZE inside

```
DATABASE_URL=postgres://casbin_rs:casbin_rs@localhost:5432/casbin
# DATABASE_URL=mysql://casbin_rs:casbin_rs@localhost:3306/casbin
# DATABASE_URL=sqlite:casbin.db
POOL_SIZE=8
```

Or you can export DATABASE_URL, POOL_SIZE

```
export DATABASE_URL=postgres://casbin_rs:casbin_rs@localhost:5432/casbin
export POOL_SIZE=8
```

**Comment by litcc** [comment]
One thing I can't understand, why must I use this variable or variable declaration file? Why can't it be optional? What if the compiled environment has no database at all, how to circumvent the problem of needing this environment variable?

**Comment by hsluoyz** [comment]
@PsiACE

**Comment by greenhandatsjtu** [comment]
> One thing I can't understand, why must I use this variable or variable declaration file? Why can't it be optional? What if the compiled environment has no database at all, how to circumvent the problem of needing this environment variable?


Hi @litcc,  `DATABASE_URL` must be set because sqlx-adapter uses `query!` marco to statically check SQL queries.

According to [docs of sqlx](https://docs.rs/sqlx/latest/sqlx/macro.query.html#requirements), to use `query!`:

- The `DATABASE_URL` environment variable must be set at **build-time** to point to a database server with the schema that the query string will be checked against. All variants of `query!()` use [dotenv](https://crates.io/crates/dotenv) so this can be in a `.env` file instead.
- Or, `sqlx-data.json` must exist at the workspace root.

To use `sqlx-data.json` , you can follow the [docs for offline mode](https://docs.rs/sqlx/latest/sqlx/macro.query.html#offline-mode-requires-the-offline-feature):

- Run `cargo install sqlx-cli`.
- In your project with `DATABASE_URL` set (or in a `.env` file) and the database server running, run `cargo sqlx prepare`.
- Check the generated `sqlx-data.json` file into version control.
- Don’t have `DATABASE_URL` set during compilation.

Your project can now be built without a database connection (you must omit `DATABASE_URL` or else it will still try to connect). To update the generated file simply run `cargo sqlx prepare` again.

> **Note**: As sqlx-adapter has generated `sqlx-data.json` for postgres, so when using postgres you don’t need provide `DATABASE_URL` or `sqlx-data.json` . But for mysql and sqlite, you must provide `DATABASE_URL` or `sqlx-data.json`

**Comment by litcc** [comment]
OK, thank you very much for your reply.
